server:
  port: 8003

spring:
  application:
    name: cloud-provider-hystrix-payment
    zipkin:
      base-url: http://localhost:9411
    sleuth:
      sampler:
      #采样率介于0到1之间,则表示全部采集
      probability: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka9001.com:9001/eureka