server:
  port: 7003
spring:
  application:
    name: cloud-provider-hystrix-order


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/

feign:
  hystrix:
    enabled: true