server:
  port: 9723

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名，一个id代表一个路由规则,只要不重复就行
          uri: http://localhost:8003         #匹配后提供服务的路由地址
          #uri: http://localhost:7001         #匹配后提供服务的路由地址
#          uri: lb://CLOUD-PAYMENT-SERVICE     #匹配后提供服务的路由地址，我们从服务名来找
          predicates:
            - Path=/payment/**                # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8003          #匹配后提供服务的路由地址
          #uri: http://localhost:7001         #匹配后提供服务的路由地址
#          uri: lb://CLOUD-PAYMENT-SERVICE     #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**             # 断言，路径相匹配的进行路由
#            - Path=/payment/lb/**             # 断言，路径相匹配的进行路由
            #- After=2020-04-02T11:34:28.670+08:00[Asia/Shanghai]
            #- Cookie=username,zpb
            #- Header=X-Request-Id, \d+       # 请求头要有X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: gateway-service-9723
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka9001.com:9001/eureka
